package br.com.econoMy.classes;

public enum SetorAplicativo {
    SALDO,
    DEPOSITO,
    TRANSFERENCIAS,
    HISTORICO_TRANSFERENCIA,
    HISTORICO_DEPOSITO,
    VERIFICAR_CHAVE_REGISTRADA,
    AVALIACAO,
    AVALIACAO_MEDIA,
    TROCAR_CHAVE,
    TROCAR_SENHA
}
